### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by matheuscumpian** [HeavyBR/open-sauced-goals#6]

**Comment by matheuscumpian** [comment]
https://github.com/HeavyBR/livebook/commit/2b3833f50ba277be02c6793e8c0eeecb943a78f2#diff-6d187acf2484b8cef1732f05219594b285193479d3b6eb122ff3e106a7844ffb

**Comment by matheuscumpian** [comment]
https://github.com/livebook-dev/livebook/compare/main...HeavyBR:improving-close-session-warning

**Comment by HeavyBR** [comment]
teste 2b3833f50ba277be02c6793e8c0eeecb943a78f2
